name: Deploy to AWS EC2

on:
  push:
    branches: [ main ] # This triggers the belt when you push code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Placibo
            git pull origin main
            # Kill the old server process on Port 80
            sudo lsof -t -i:80 | xargs sudo kill -9 || true
            # Start the server again in the background
            sudo nohup /home/ubuntu/.local/share/virtualenvs/Placibo-HhCy19eU/bin/python3 manage.py runserver 0.0.0.0:80 &